FROM node:23-alpine3.20

WORKDIR /notification-service

COPY ./package*.json ./
COPY ./tsconfig.json ./
COPY .npmrc ./
COPY tools  ./tools 
COPY src ./src

RUN ls -a
RUN npm install && npm install -g nodemon

EXPOSE 4000

CMD ["npm", "run", "dev"]

